name: "colmena build"
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update and Upgrade system
      run: |
         DEBIAN_FRONTEND=noninteractive
         sudo apt-get update -q -y && sudo apt-get upgrade -q -y
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-25.11

    - uses: actions/create-github-app-token@v2
      id: app-token
      with:
        # required
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
    - uses: actions/checkout@v6
      with:
        token: ${{ steps.app-token.outputs.token }}
        submodules: true
        persist-credentials: false
    - name: start nix-shell once
      run: nix-shell --run "echo \"success\""
    - name: colmena build
      run: nix-shell --run "colmena build -v"
